name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      # Build Frontend
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
      
      - name: Build frontend
        run: |
          cd frontend
          npm run build
      
      # Build Backend
      - name: Install backend dependencies
        run: |
          cd backend
          npm install
      
      - name: Build backend
        run: |
          cd backend
          npm run build || echo "No build script found"
      
      # Copy frontend build to backend static folder
      - name: Copy frontend to backend
        run: |
          mkdir -p backend/public
          cp -r frontend/dist/* backend/public/ || cp -r frontend/build/* backend/public/
      
      # Create deployment package
      - name: Create deployment package
        run: |
          cd backend
          zip -r ../deploy.zip . -x "node_modules/*" ".git/*"
      
      # Deploy to Azure
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'expandev-01'
          package: deploy.zip
          clean: true
          restart: true